# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: e84e1df
_src_path: gh:scipp/copier_template
description: Input / output for SQW spectroscopy files.
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: scipp
orgname: scipp
prettyname: SQOmega
projectname: sqomega
related_projects: Scipp,ESSspectroscopy
year: 2024
